language: node_js
node_js:
  - "node"
  - "5"
  - "4"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
git:
  depth: 3
install: npm install gulp gulp-util gulp-file yargs@"~3.15.0" sinon istanbul coveralls
before_script:
  - 'gulp build:dev'
after_success:
  - 'npm run coveralls'
